---
- hosts: web
  sudo: yes
  tasks:
  - name: install nginx
    apt: name=nginx state=installed update_cache=yes
    become: yes
  - name: start Service
    service: name=nginx state=started
    become: yes
  - name: run a command
    command: netstat -ntpl
    become: yes
  - name: install ssh
    apt: name=ssh state=installed update_cache=yes
    become: yes
      
